feat: tratamento de exceções
Rinyaresu/ruby4noobs pull request #6
Opened 2023-08-26 01:01 UTC by Nandosts

O novo arquivo Markdown "tratamento-de-excecoes.md" abrange os seguintes tópicos:

1. Uma introdução ao tratamento de exceções e sua importância na programação.

2. Referência à documentação oficial de exceções em Ruby, com um link para mais detalhes sobre os tipos de exceção disponíveis.

3. Uso do bloco `begin`, `rescue` e `end` para capturar exceções e executar blocos de código alternativos quando erros ocorrem.

4. Exemplos práticos de tratamento de exceções, incluindo lidar com erros de divisão por zero e erros de tipo.

5. Demonstração de tratamento de exceções em cadeia, mostrando como capturar múltiplos tipos de exceção.

6. Exemplos de lançamento de exceções pré-definidas, como `ZeroDivisionError`, e como capturá-las para fornecer mensagens de erro personalizadas.

7. Exemplos de criação e lançamento de exceções personalizadas usando classes derivadas de `StandardError`.

8. Dicas e boas práticas sobre o uso adequado de tratamento de exceções em Ruby.

## Próximos Passos

Este conteúdo inicial fornece uma base sólida para entender o tratamento de exceções em Ruby. No entanto, há espaço para expandir com mais exemplos complexos e tópicos avançados, como o uso do bloco `ensure` e a hierarquia de exceções em Ruby.

## Comentários

Estou aberto a qualquer feedback ou sugestões para melhorias neste conteúdo. O objetivo é torná-lo útil e compreensível para programadores iniciantes e intermediários que desejam aprender sobre tratamento de exceções em Ruby.

Agradeço antecipadamente por revisar este PR e contribuir com seus comentários.

2023-08-28 22:37 UTC, Rinyaresu approved these changes
LGTM!

![image](https://media.tenor.com/o04yfBNtmRcAAAAM/anime-approve.gif)

2023-08-29 02:21 UTC, Rinyaresu requested changes
Fiz umas mudanças no projeto no PR #7. Dá uma olhada e ajusta o PR pra ficar nos trinques, beleza?

2023-08-30 00:55 UTC, Nandosts commented
> Fiz umas mudanças no projeto no PR #7. Dá uma olhada e ajusta o PR pra ficar nos trinques, beleza?

Opa, alterei aqui pra seguir o formato, acredito que está nos trinques, bonitão já

2023-08-30 02:44 UTC, Rinyaresu approved these changes
Nice, ficou maneiro, pode fazer o merge

2023-08-30 08:57 UTC, Nandosts commented
> Nice, ficou maneiro, pode fazer o merge

Único problema é que não tenho permissão k k 

![image](https://github.com/Rinyaresu/ruby4noobs/assets/65089035/89ba0eba-721b-4719-b86f-3f7bdb813024)

2023-08-30 12:20 UTC, merged

2023-08-30 12:21 UTC, Rinyaresu commented
> > Nice, ficou maneiro, pode fazer o merge
> 
> 
> 
> Único problema é que não tenho permissão k k 
> 
> 
> 
> ![image](https://github.com/Rinyaresu/ruby4noobs/assets/65089035/89ba0eba-721b-4719-b86f-3f7bdb813024)
> 
> 

Foi mal tinha esquecido disso ;-;